### ISSUE TITLE
Astral can not be installed if pytz is not previously installed

### ISSUE THREAD

**Issue by Nekmo** [sffjunkie/astral#8]
The setup.py file imports the __init__.py to get the version, but the import fails because pytz is not installed. 

```
Collecting astral from git+https://github.com/sffjunkie/astral.git@master#egg=astral (from -r requirements.txt (line 73))
  Cloning https://github.com/sffjunkie/astral.git (to master) to /tmp/pip-build-isievuvt/astral
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "src/astral.py", line 75, in <module>
        import pytz
    ImportError: No module named 'pytz'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-isievuvt/astral/setup.py", line 11, in <module>
        from astral import __version__ as astral_version
      File "src/astral.py", line 77, in <module>
        raise ImportError(('The astral module requires the '
    ImportError: The astral module requires the pytz module to be available.
```

My recommendation is to put the code in another file and use the __init__.py for the __version__. 
Another option is to put the version in the setup.py

**Comment by sffjunkie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Set version number directly](https://trello.com/c/22IoCdW4/4-set-version-number-directly)

**Comment by sffjunkie** [comment]
The version number is now set directly in setup.py.
